apiVersion: v1
kind: Pod
metadata:
  name: api
  labels:
    app: api
spec:
  containers:
    - name: api
      image: menachemkazido/fast-mongodb:latest
      ports:
        - containerPort: 8000
      env:
        - name: DB_HOST
          value: mongodb-service
        - name: DB_PORT
          value: '27017'
        - name: DB_NAME
          value: contacts_db
